export const ACTIONS = ({
  LOADING: 'LOADING',
  STOP_LOADING: 'STOP_LOADING',
  GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
  GET_ALL_COUNTRIES_ERROR: 'GET_ALL_COUNTRIES_ERROR',
  GET_SPIN: 'GET_SPIN',
  GET_SPIN_ERROR: 'GET_SPIN_ERROR',
});
